//! Raw FFI bindings to the llama.cpp C API.
//!
//! This crate is auto-generated by `bindgen` and should not be used directly.
//! Use the safe `llama-core` wrapper instead.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]
#![allow(unsafe_op_in_unsafe_fn)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_backend_init_free() {
        unsafe {
            llama_backend_init();
            llama_backend_free();
        }
    }
}
